name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          # - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          architecture: x64
          check-latest: true
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Build frontend
        run: |
          cd client
          npm ci
          npm run build
      - name: Upload frontend static files
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: server-node/static
      - name: Build executable
        run: |
          if [ $RUNNER_OS == "Windows" ]; then
            ext=".exe"
          else
            ext=""
          fi
          cd server-node
          npm ci
          npm install --no-save caxa
          npx caxa \
            --input . \
            --output "../dist/lanclip${ext}" \
            --exclude \
              ".*" \
              "config.json" \
              "package-lock.json" \
            -- \
              "{{caxa}}/node_modules/.bin/node" \
              "{{caxa}}/main.js"
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: lanclip-${{ runner.os }}
          path: dist
      - name: Validate release config
        if: runner.os == 'Linux'
        run: node scripts/validate-release-config.mjs
